Laravel ecommerce RMA update in v2.0
bagisto/bagisto-rma pull request #5
Opened 2023-11-02 13:30 UTC by antuchaudharyqlo246

2023-11-03 19:49 UTC, ghermans requested changes

2023-11-03 19:49 UTC, ghermans commented on src/Config/system.php
> +        'info'      => 'Return merchandise authorization.',
Please do not use static text, use the translation files instead.

2023-11-03 19:49 UTC, ghermans commented on src/Config/system.php
>          'info'      => 'E-commerce merchant to permit the return of a product.',
Please do not use static text, use the translation files instead.

2025-01-30 05:46 UTC, vivek-webkul commented
Closing this invalid PR

2025-01-30 05:46 UTC, closed without merging